import type { Pattern } from "./types";

export const REFLECTION_PATTERNS: readonly Pattern[] = [
  {
    id: "uncertainty",
    keywords: [
      "anxious",
      "nervous",
      "unsure",
      "waiting",
      "future",
      "uncertain",
      "scared",
      "worry",
      "worried",
      "anxiety",
      "unknown",
      "not sure",
      "on edge",
      "racing thoughts",
    ],
    anchors: [
      "what if",
      "interview",
      "might happen",
      "what happens if",
      "if i fail",
      "if i don't",
      "if i dont",
    ],
    suggest:
      "Much of what you wrote circles an outcome that is still unresolved, especially what happens next.",
    possibility:
      "One possibility is that the gap between now and an outcome is getting filled with rehearsals: sharp little scenes where things go wrong.",
    tryNext:
      "Write the scenario you keep replaying in one sentence. Under it, add one sentence about what you would do later that same day if it happened.",
  },
  {
    id: "control",
    keywords: [
      "frustrated",
      "annoyed",
      "fix",
      "control",
      "should",
      "plan",
      "stuck",
      "unfair",
      "doesn't work",
      "doesnt work",
      "won't",
      "wont",
      "ignored",
      "dismissed",
    ],
    anchors: [
      "out of my hands",
      "why won't",
      "why wont",
      "won't listen",
      "wont listen",
      "not listening",
      "they never",
      "i can't make",
      "i cant make",
    ],
    suggest:
      "You keep bumping into a mismatch between what you want to steer and what actually moves when you push.",
    possibility:
      "One possibility is that part of the strain is the gap between effort and leverage—wanting a different response than the situation is offering.",
    tryNext:
      "Make two short lists: what you can change today with your actual power, and what you can only adjust your response to.",
  },
  {
    id: "avoidance",
    keywords: [
      "avoid",
      "avoiding",
      "procrastinating",
      "putting off",
      "dreading",
      "delay",
      "postpone",
      "haven't started",
      "havent started",
      "keep putting",
      "someday",
    ],
    anchors: [
      "keep putting off",
      "putting it off",
      "deal with it tomorrow",
      "i'll deal with it tomorrow",
      "ill deal with it tomorrow",
      "i'll do it later",
      "ill do it later",
      "keep avoiding",
      "been avoiding",
      "dreading starting",
      "not starting",
      "knew i should start",
      "can't make myself",
      "cant make myself",
    ],
    suggest:
      "There is a steady pull toward ‘not now’—as if moving closer would make the weight undeniable.",
    possibility:
      "One possibility is that this looks like procrastination from the outside, while from the inside it feels more like hesitation, fatigue, or waiting for the moment to feel safer.",
    tryNext:
      "Choose a first step so small it feels almost silly (one sentence, one minute), and stop after that step on purpose.",
  },
  {
    id: "burnout",
    keywords: [
      "tired",
      "exhausted",
      "drained",
      "numb",
      "overwhelmed",
      "too much",
      "depleted",
      "overwork",
      "no break",
      "burnout",
    ],
    anchors: [
      "burned out",
      "burnt out",
      "can't keep up",
      "cant keep up",
      "no energy",
      "running on empty",
      "left to give",
      "anything left",
      "keeping up",
    ],
    suggest:
      "Your wording suggests thin reserves: ordinary tasks seem to cost more than they used to, even when the schedule looks familiar.",
    possibility:
      "One possibility is that you are closer to empty than the schedule suggests, so the signal shows up as overload, numbness, or a short fuse.",
    tryNext:
      "Remove or postpone one commitment this week that is not truly required—not to optimize, just to buy a little air.",
  },
  {
    id: "grief",
    keywords: [
      "miss",
      "gone",
      "ended",
      "empty",
      "grief",
      "died",
      "death",
      "no longer",
      "funeral",
      "loss",
    ],
    anchors: [
      "passed away",
      "not here anymore",
      "breakup",
      "broke up",
      "they left",
      "since they left",
      "left me",
      "still miss",
      "still carrying",
      "more than i expected",
      "after it ended",
      "everything feels different",
      "everything feels different now",
      "everything feels wrong",
      "everything feels empty",
      "old photos",
    ],
    suggest:
      "You keep brushing up against a before—something absent, ended, or not like it used to be.",
    possibility:
      "One possibility is that adjustment is leaking into ordinary language: flatness, irritability, or the sense that familiar things no longer fit the same way.",
    tryNext:
      "In two lines: what changed (fact), and what you miss (feeling). Keep them separate so neither has to do the other’s job.",
  },
  {
    id: "guilt",
    keywords: [
      "guilt",
      "guilty",
      "ashamed",
      "blame",
      "failed",
      "let down",
      "shouldn't have",
      "shouldnt have",
      "feel bad",
      "that conversation",
    ],
    anchors: [
      "how i handled",
      "should have said",
      "said it differently",
      "my fault",
      "should have",
      "disappointed myself",
    ],
    suggest:
      "Your answers land hard on your own choices, as if the whole story can be reduced to one responsible person.",
    possibility:
      "One possibility is that accountability and blame got braided together—so every detail feels like evidence instead of information.",
    tryNext:
      "Write one sentence that names a limit or constraint you did not choose, even if it is small.",
  },
] as const;
